// This file is generated by Slice Machine. Update with care!

import BenefitsSlice from './BenefitsSlice/BenefitsSlice'

export { BenefitsSlice }

export const components = {
  benefits_slice: BenefitsSlice,
}
